POST https://fso-exercises-p4.onrender.com/api/blogs
content-type: application/json

{
    "title": "Test1",
    "author": "Ale",
    "url": "https://blog.carleslc.me",
    "likes": 12,
    "user": "Ale"
}

###
POST https://fso-exercises-p4.onrender.com/api/users
content-type: application/json

{
    "username": "Ale",
    "name": "Ale",
    "password": "1234"
}